---
title: "Untitled"
output: html_document
date: "2026-07-13"
---

```{r setup, include=FALSE}
#| label: setup

library(metR)
library(ggplot2)
library(data.table)
library(here)
library(cowplot)
library(ggside)
library(patchwork)

global_map <- rnaturalearth::ne_coastline()
models_in_gadi <- c("CMCC-ESM2", "EC-Earth3", "INM-CM4-8", "INM-CM5-0", 
                    "MPI-ESM1-2-HR", "NorESM2-MM", "EC-Earth3-CC", "EC-Earth3-Veg",
                    "EC-Earth3-Veg-LR", "GFDL-CM4")
```

## Cliamtology and trends

```{r}
file_list <- c(Sys.glob(here("data/temp/deltat/deltap97.5_*historical_*J*.nc")),
               Sys.glob(here("data/old/eke_mean/eke_*historical_*J*.nc")))

delta <- purrr::map(file_list, function(f) {
  
  message(f)
  meta <- unglue::unglue(basename(f), "{var}_{model}_{scenario}_{season}.nc")
  
  
  if (meta[[1]][["var"]] == "eke") {
    var <- "ua"
    file_scenario <- Sys.glob(here(paste0("data/old/eke_mean/", meta[[1]][["var"]], "_", meta[[1]][["model"]], "_ssp585_", meta[[1]][["season"]], ".nc")))
  } else if (meta[[1]][["var"]] == "deltap97.5") {
    var <- "tasmax"
    file_scenario <- Sys.glob(here(paste0("data/temp/deltat/", meta[[1]][["var"]], "_", meta[[1]][["model"]], "_ssp585_", meta[[1]][["season"]], ".nc")))
    # meta[[1]][["var"]] <- "deltat"
  } 
  
  
  
  ReadNetCDF(f, vars = c(hist = var)) |> 
    _[, let(ssp585 = ReadNetCDF(file_scenario, vars = c(ssp585 = var), out = "vector")[[1]])] |> 
    _[, let(model = meta[[1]][["model"]],
            var = meta[[1]][["var"]],
            season = meta[[1]][["season"]],
            change = ssp585 / hist,
            diff = ssp585 - hist,
            lat = round(lat, digits = 8),
            plev = NULL)] |> 
    _[]
  
}) |> rbindlist() |> 
  _[, let(var = fifelse(var == "deltap97.5", "deltat", var))]

ta <- purrr::map(Sys.glob(here("data/ta/*hist*J*.nc")), function(f) {
  
  message(f)
  meta <- unglue::unglue(basename(f), patterns = c("{var}_{model}_historical_{season}.nc"))
  
  file_scenario <- Sys.glob(here(paste0("data/", meta[[1]][["var"]], "/", 
                                        meta[[1]][["var"]], "_", meta[[1]][["model"]], "_ssp585_", meta[[1]][["season"]], ".nc")))
  
  var <- meta[[1]][["var"]]
  
  ReadNetCDF(f, vars = c(hist = var), subset = list(plev = 85000)) |> 
    _[, let(ssp585 = ReadNetCDF(file_scenario, vars = c(ssp585 = var), 
                                subset = list(plev = 85000),
                                out = "vector")[[1]])] |> 
    _[, let(model = meta[[1]][["model"]],
            var = var,
            season = meta[[1]][["season"]],
            lat = round(lat, digits = 8),
            hist = metR:::.derv(hist, lat)*(180/pi/6371000),
            ssp585 = metR:::.derv(ssp585, lat)*(180/pi/6371000)), by = .(lon)] |> 
    _[, let(change = ssp585 / hist,
            diff = ssp585 - hist,
            plev = NULL)]
  
}) |> rbindlist() 

data <- rbindlist(list(delta, ta)) |> 
  _[, let(land = MaskLand(lon, lat))] |>
  _[, let(land = factor(land, labels = c("Sea", "Land")))]
```

```{r}
topo <- rcdo::cdo_topo(grid = "r360x180") |> 
  rcdo::cdo_execute(options = "-f nc") |> 
  ReadNetCDF()

sig <- data |> 
  _[(model %in% models_in_gadi) & var == "deltat"] |>
  dcast(lat + lon + model + season ~ var, value.var = "diff") |> 
  _[, .(sig = sum(sign(deltat), na.rm = TRUE)), by = .(lon, lat)] 

data |> 
  _[(model %in% models_in_gadi) & is.finite(change)] |>
  dcast(lat + lon + model + season ~ var, value.var = "diff") |> 
  _[, .(mean_dt = mean(deltat, na.rm = TRUE)), by = .(lon, lat, season)] |> 
  # _[]
  ggplot(aes(ConvertLongitude(lon), lat)) +
  geom_contour_fill(aes(z = mean_dt, fill = after_stat(level)),
                    breaks = c(-Inf, seq(-8, 8, 0.5), Inf)) +
  scale_fill_divergent_discretised(name = "days/year", mid = "#f7f7f7",
                                   guide = guide_colorbar(barheight = 0.5),
                                   labels = function(x) JumpBy(x, 2, fill = "")) +
  geom_sf(data = global_map, inherit.aes = FALSE, fill = NA, linewidth = 0.2) +
  geom_point(data = sig[is.cross(lon, lat, skip = 1) & abs(sig) >= 9], alpha = 0.3, shape = 4, size = 0.1) +
  # ggnewscale::new_scale_fill() +
  # geom_contour_fill(data = topo, aes(ConvertLongitude(lon), lat, z = topo), breaks = c(1300, Inf), fill = "grey90") +
  scale_y_latitude(breaks = seq(-80, 80 , 20)) +
  coord_sf(expand = FALSE, xlim = c(-179, 180)) +
  labs(x = NULL, y = NULL, fill = "days/year") +
  facet_wrap(~season) +
  theme_minimal(base_size = 12) +
  theme(legend.position = "bottom",
        legend.frame = ggplot2::element_rect(color = "black", linewidth = 0.4),
        legend.key.width = grid::unit(1, 'null'),
        legend.margin = unit(c(-1, 0, -1, 0), units = "cm"), 
        # axis.text.y = element_blank(),
        # axis.ticks.y = element_blank(),
        plot.margin = unit(c(-0.5, 0 , -0.5, 0), units = "cm")) 
```

```{r}
data |> 
  _[var == "deltat"] |> 
  _[(model %in% models_in_gadi) & is.finite(change)] |>
  _[, .(mean_deltat = mean(hist)), by = .(lon, lat, season)] |> 
  ggplot(aes(ConvertLongitude(lon), lat)) +
  geom_contour_fill(aes(z = mean_deltat, fill = after_stat(level))) +
  geom_sf(data = global_map, inherit.aes = FALSE, fill = NA, linewidth = 0.2) +
  scale_fill_viridis_d( guide = guide_colorsteps(barheight = 0.5)) +
  scale_y_latitude(breaks = seq(-80, 80 , 20)) +
  coord_sf(expand = FALSE, xlim = c(-179, 180)) +
  labs(x = NULL, y = NULL, fill = "days/year") +
  facet_wrap(~season) +
  theme_minimal(base_size = 12) +
  theme(legend.position = "bottom",
        legend.frame = ggplot2::element_rect(color = "black", linewidth = 0.4),
        legend.key.width = grid::unit(.5, 'null'),
        legend.margin = unit(c(-1, 0, -1, 0), units = "cm"), 
        # axis.text.y = element_blank(),
        # axis.ticks.y = element_blank(),
        plot.margin = unit(c(-0.5, 0 , -0.5, 0), units = "cm")) 
```

```{r}
data |> 
  _[var == "deltat"] |> 
  _[(model %in% models_in_gadi) & is.finite(change)] |>
  # _[season == "DJF" & !(model %in% c("GFDL-CM4"))] |> 
  _[season == "JJA"] |>
  # _[, .(mean_deltat = mean(hist)), by = .(lon, lat, season)] |> 
  ggplot(aes(ConvertLongitude(lon), lat)) +
  geom_contour_fill(aes(z = hist, fill = after_stat(level))) +
  geom_sf(data = global_map, inherit.aes = FALSE, fill = NA, linewidth = 0.2) +
  scale_fill_viridis_d( guide = guide_colorsteps(barheight = 0.5)) +
  scale_y_latitude(breaks = c(seq(-80, 80 , 20), Inf)) +
  coord_sf(expand = FALSE, xlim = c(-179, 180)) +
  labs(x = NULL, y = NULL, fill = "days/year") +
  facet_wrap(~model) +
  theme_minimal(base_size = 12) +
  theme(legend.position = "bottom",
        legend.frame = ggplot2::element_rect(color = "black", linewidth = 0.4),
        legend.key.width = grid::unit(.5, 'null'),
        legend.margin = unit(c(-1, 0, -1, 0), units = "cm"), 
        # axis.text.y = element_blank(),
        # axis.ticks.y = element_blank(),
        plot.margin = unit(c(-0.5, 0 , -0.5, 0), units = "cm"))
```


```{r}
delta |> 
  _[var == "deltat"] |> 
  _[(model %in% models_in_gadi) & is.finite(change)] |>
  # _[season == "DJF" & !(model %in% c("GFDL-CM4"))] |> 
  # _[season == "JJA"] |>
  # _[, .(mean_deltat = mean(hist)), by = .(lon, lat, season)] |> 
  ggplot(aes(ConvertLongitude(lon), lat)) +
  geom_contour_fill(aes(z = hist, fill = after_stat(level))) +
  geom_sf(data = global_map, inherit.aes = FALSE, fill = NA, linewidth = 0.2) +
  scale_fill_viridis_d( guide = guide_colorsteps(barheight = 0.5)) +
  scale_y_latitude(breaks = c(seq(-80, 80 , 20), Inf)) +
  coord_sf(expand = FALSE, xlim = c(-179, 180)) +
  labs(x = NULL, y = NULL, fill = "days/year") +
  facet_wrap(~model) +
  theme_minimal(base_size = 12) +
  theme(legend.position = "bottom",
        legend.frame = ggplot2::element_rect(color = "black", linewidth = 0.4),
        legend.key.width = grid::unit(.5, 'null'),
        legend.margin = unit(c(-1, 0, -1, 0), units = "cm"), 
        # axis.text.y = element_blank(),
        # axis.ticks.y = element_blank(),
        plot.margin = unit(c(-0.5, 0 , -0.5, 0), units = "cm"))
```


```{r}
change <- data |> 
  _[(model %in% models_in_gadi)] |>
  dcast(lat + lon + model + season + land ~ var, value.var = "diff") |> 
  
  _[, let(region = fcase(lat %between% c(25, 65), "NH",
                         lat %between% c(-65, -25), "SH",
                         default = NA))] |> 
  _[, .(mean_eke = weighted.mean(eke, w = cos(lat*pi/180), na.rm = TRUE),
        mean_dt_dy = weighted.mean(ta, w = cos(lat*pi/180), na.rm = TRUE),
        mean_deltat = weighted.mean(deltat, w = cos(lat*pi/180), na.rm = TRUE)), by = .(region, land, model, season)] |> 
  _[, let(mean_dt_dy = fifelse(region == "NH", -mean_dt_dy, mean_dt_dy))] |> 
  na.omit()

gradt <- change |> 
  ggplot(aes(mean_dt_dy*1000, mean_deltat)) +
  geom_point(aes(color = region, shape = land), size = 2) +
  geom_smooth(aes(colour = region), method = "lm", se = FALSE) +
  scale_color_manual(values = c("cyan4", "orange")) +
  labs(x = latex2exp::TeX("$\\partial \\bar{T} / \\partial y$ change (K/km)"), 
       y = latex2exp::TeX("$\\Delta T_{2.5}$ frequency change (days/year)"),
       color = NULL, shape = NULL) +
  coord_cartesian(ylim = c(-1.5, 1.5)) +
  facet_wrap(~season) +
  theme_minimal() +
  theme(legend.position = "inside",
        legend.position.inside = c(0.73, 0.1),
        legend.direction = "horizontal",
        legend.box.background = element_rect(fill = "#fbfbfb", color = "#fbfbfb"),
        legend.margin = margin(-2, 2, 1, 2, unit = "mm"),
        panel.background = element_rect(fill = "#fbfbfb", color = NA))

eke <- change |> 
  ggplot(aes(mean_eke, mean_deltat)) +
  geom_point(aes(color = region, shape = land), size = 2) +
  geom_smooth(aes(colour = region), method = "lm", se = FALSE) +
  scale_color_manual(values = c("cyan4", "orange")) +
  labs(x = latex2exp::TeX("EKE change ($m^2 s^{-2}$)"), 
       y = NULL,
       color = NULL, shape = NULL) +
  coord_cartesian(ylim = c(-1.5, 1.5)) +
  facet_wrap(~season) +
  theme_minimal() +
  theme(legend.position = "none",
        # legend.position.inside = c(0.83, 0.08),
        # legend.direction = "horizontal",
        # legend.background = element_rect(fill = "#fbfbfb", color = "#fbfbfb"),
        # legend.margin = margin(-3, 0, 0, 0, unit = "mm"),
        panel.background = element_rect(fill = "#fbfbfb", color = NA))

plot_grid(gradt, eke, ncol = 1, 
          # label_x = 0.12, label_y = 0.98,
          label_fontface = "plain", 
          label_colour = "black",
          rel_widths = c(1, 1))
```

